server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:embedded-database
    username: root
    password: root

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: accounts/src/main/java/com/askie01/accounts/logs/accounts-microservice.log
  logback:
    rolling-policy:
      max-file-size: 10MB
      max-history: 30
  level:
    root: ERROR
    com:
      zaxxer:
        hikari: INFO
    org:
      springframework: INFO
      hibernate: INFO
      apache:
        catalina: INFO
      askie01:
        accounts: DEBUG

build:
  version: 1.0.0

accounts:
  message: "{cipher}f8920e5d61d24ba447e39201d213740e92ac7a4fe23f2e7a8a7027f29930ba07157425f16b8473ec13f69a9abc0f380654f757714845f06bfe8bb75b210a9a00c6a72f369c5e0c87d8bd7f47c8dc36ddbfcd6b3fef4113481d6059260c04bf01"
  contact-details:
    name: "{cipher}342a819e905d5d1bac4ef6022077dc6f1ba679afaec46f5e0ad06a85e62e2795a5465c51dfe3ccbf80545fdd7d1137d2"
    email: "{cipher}56e6e78bdb19e7d54c68147b8718d8c8c6f473b646a51bd7f6fa4a1b11b5c92c6cecf03045d19e58b7718918bbbf6a05"
  on-call-support:
    - "{cipher}2574c1c1151465b56f38975f6ff7e76b4a68c92b5a7282dd0817f3ab858699b9"
    - "{cipher}8c6ce0e75d5d50cf62cf99d8f0389746741dec6fe643437b0d213ad23e48060a"